=begin
#CDR API

#Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveCdrApiClient::FileSanitizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileSanitizationApi' do
  before do
    # run before each test
    @instance = CloudmersiveCdrApiClient::FileSanitizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileSanitizationApi' do
    it 'should create an instance of FileSanitizationApi' do
      expect(@instance).to be_instance_of(CloudmersiveCdrApiClient::FileSanitizationApi)
    end
  end

  # unit tests for file
  # Content Disarm and Reconstruction on a File
  # Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [String]
  describe 'file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_advanced
  # Advanced Content Disarm and Reconstruction on a File
  # Processes the input file via CDR to produce a secured output file with advanced scan options and response headers containing scan metadata.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :allow_executables Set to false to block executable files (EXE, DLL, etc.)
  # @option opts [BOOLEAN] :allow_invalid_files Set to false to block files that are not valid for their detected type
  # @option opts [BOOLEAN] :allow_scripts Set to false to block script files. PDF and Office macro sanitization still runs regardless.
  # @option opts [BOOLEAN] :allow_password_protected_files Set to false to block password-protected files
  # @option opts [BOOLEAN] :allow_macros Set to false to block files containing macros. Office macro removal still runs regardless.
  # @option opts [BOOLEAN] :allow_xml_external_entities Set to false to block XML files with external entity references (XXE)
  # @option opts [BOOLEAN] :allow_insecure_deserialization Set to false to block files with insecure deserialization patterns
  # @option opts [BOOLEAN] :allow_html Set to false to block HTML files
  # @option opts [BOOLEAN] :allow_unsafe_archives Set to false to block archive files flagged as unsafe (e.g., zip bombs)
  # @option opts [BOOLEAN] :allow_ole_embedded_object Set to false to block files with embedded OLE objects
  # @option opts [BOOLEAN] :allow_unwanted_action Set to false to block files with unwanted actions
  # @option opts [String] :restrict_file_types Comma-separated list of allowed file extensions (e.g., \&quot;.pdf,.docx,.xlsx\&quot;). Files not matching will be blocked.
  # @option opts [File] :input_file Input document to CDR process
  # @return [String]
  describe 'file_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_to_pdf
  # Content Disarm and Reconstruction on a File with PDFA Output
  # Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [String]
  describe 'file_to_pdf test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_to_pdf_advanced
  # Advanced Content Disarm and Reconstruction on a File with PDFA Output
  # Processes the input file via CDR to produce a secured PDF/A output file with advanced scan options and response headers containing scan metadata.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :allow_executables Set to false to block executable files (EXE, DLL, etc.)
  # @option opts [BOOLEAN] :allow_invalid_files Set to false to block files that are not valid for their detected type
  # @option opts [BOOLEAN] :allow_scripts Set to false to block script files. PDF and Office macro sanitization still runs regardless.
  # @option opts [BOOLEAN] :allow_password_protected_files Set to false to block password-protected files
  # @option opts [BOOLEAN] :allow_macros Set to false to block files containing macros. Office macro removal still runs regardless.
  # @option opts [BOOLEAN] :allow_xml_external_entities Set to false to block XML files with external entity references (XXE)
  # @option opts [BOOLEAN] :allow_insecure_deserialization Set to false to block files with insecure deserialization patterns
  # @option opts [BOOLEAN] :allow_html Set to false to block HTML files
  # @option opts [BOOLEAN] :allow_unsafe_archives Set to false to block archive files flagged as unsafe (e.g., zip bombs)
  # @option opts [BOOLEAN] :allow_ole_embedded_object Set to false to block files with embedded OLE objects
  # @option opts [BOOLEAN] :allow_unwanted_action Set to false to block files with unwanted actions
  # @option opts [String] :restrict_file_types Comma-separated list of allowed file extensions (e.g., \&quot;.pdf,.docx,.xlsx\&quot;). Files not matching will be blocked.
  # @option opts [File] :input_file Input document to CDR process
  # @return [String]
  describe 'file_to_pdf_advanced test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
