=begin
#CDR API

#Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveCdrApiClient::FileSanitizationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileSanitizationApi' do
  before do
    # run before each test
    @instance = CloudmersiveCdrApiClient::FileSanitizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileSanitizationApi' do
    it 'should create an instance of FileSanitizationApi' do
      expect(@instance).to be_instance_of(CloudmersiveCdrApiClient::FileSanitizationApi)
    end
  end

  # unit tests for file
  # Complete Content Disarm and Reconstruction on an Input File, and output in same file format
  # Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [nil]
  describe 'file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_to_pdf
  # Complete Content Disarm and Reconstruction on an Input File with PDF/A Output
  # Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :input_file Input document, or photos of a document, to extract data from
  # @return [nil]
  describe 'file_to_pdf test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
