=begin
#CDR API

#Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-cdr-api-client/api_client'
require 'cloudmersive-cdr-api-client/api_error'
require 'cloudmersive-cdr-api-client/version'
require 'cloudmersive-cdr-api-client/configuration'

# Models

# APIs
require 'cloudmersive-cdr-api-client/api/file_sanitization_api'

module CloudmersiveCdrApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveCdrApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
